// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using assignment1C_.Models;

#nullable disable

namespace assignment1C_.Migrations
{
    [DbContext(typeof(ManagerContext))]
    partial class ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("assignment1C_.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Category = 0,
                            CategoryId = 1,
                            Email = "juangg@gmail.com",
                            FirstName = "Juan",
                            LastName = "Guerro",
                            Organization = "RDP",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ContactId = 2,
                            Category = 0,
                            CategoryId = 2,
                            Email = "elara.starseeker@stellarnet.com ",
                            FirstName = "Elara",
                            LastName = "Starseeker",
                            Organization = "Stellar Explorations",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            ContactId = 3,
                            Category = 0,
                            CategoryId = 5,
                            Email = "cassia.moonshade@lunarchive.us ",
                            FirstName = "Cassia",
                            LastName = "Moonshade",
                            Organization = "Celestial Archives",
                            PhoneNumber = "7788990011"
                        },
                        new
                        {
                            ContactId = 4,
                            Category = 0,
                            CategoryId = 4,
                            Email = "thorne.blackthorn@shadowcraft.io ",
                            FirstName = "Thorne",
                            LastName = "Blackthorn",
                            Organization = "Shadowbound Guild",
                            PhoneNumber = "9988776655"
                        },
                        new
                        {
                            ContactId = 5,
                            Category = 0,
                            CategoryId = 3,
                            Email = "mira.luminaris@lightweave.org ",
                            FirstName = "Mira",
                            LastName = "Luminaris",
                            Organization = "Weavers of Dawn",
                            PhoneNumber = "1122334455"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
